### Position Prediction
POST http://localhost:8081/fifa/players/predict-position
Content-Type: application/json

{
  "name": "H. Maguire",
  "fullName": "Harry Maguire",
  "birthDate": "1993-03-05",
  "age": 28,
  "heightCm": 193.04,
  "weightKgs": 99.8,
  "nationality": "England",
  "overallRating": 82,
  "potential": 85,
  "valueEuro": 3400000.0,
  "wageEuro": 77000.0,
  "preferredFoot": "RIGHT",
  "internationalReputation": 1,
  "weakFoot": 3,
  "skillMoves": 2,
  "workRate": "High/ High",
  "bodyType": "Stocky",
  "releaseClauseEuro": 46400000.0,
  "clubTeam": "FC Barcelona",
  "clubRating": "78.0",
  "clubJerseyNumber": 15.0,
  "clubJoinDate": "2022-06-15",
  "contractEndYear": 2024,
  "nationalTeam": "England",
  "nationalRating": 82.0,
  "nationalTeamPosition": "LCB",
  "nationalJerseyNumber": 6.0,
  "crossing": 44,
  "finishing": 43,
  "headingAccuracy": 87,
  "shortPassing": 77,
  "volleys": 41,
  "dribbling": 70,
  "curve": 38,
  "freekickAccuracy": 46,
  "longPassing": 72,
  "ballControl": 76,
  "acceleration": 39,
  "sprintSpeed": 54,
  "agility": 52,
  "reactions": 79,
  "balance": 58,
  "shotPower": 68,
  "jumping": 74,
  "stamina": 68,
  "strength": 89,
  "longShots": 45,
  "aggression": 84,
  "interceptions": 78,
  "positioning": 61,
  "vision": 60,
  "penalties": 44,
  "composure": 79,
  "marking": 81,
  "standingTackle": 84,
  "slidingTackle": 81,
  "GKDiving": 14,
  "GKHandling": 16,
  "GKKicking": 9,
  "GKPositioning": 14,
  "GKReflexes": 9
}

### Price Prediction
POST http://localhost:8081/fifa/players/predict-price
Content-Type: application/json

{
  "name": "H. Maguire",
  "fullName": "Harry Maguire",
  "birthDate": "1993-03-05",
  "age": 26,
  "heightCm": 193.04,
  "weightKgs": 99.8,
  "nationality": "England",
  "overallRating": 82,
  "potential": 85,
  "wageEuro": 77000.0,
  "preferredFoot": "RIGHT",
  "internationalReputation": 1,
  "weakFoot": 3,
  "skillMoves": 2,
  "workRate": "High/ High",
  "bodyType": "Stocky",
  "releaseClauseEuro": 46400000.0,
  "clubTeam": "Leicester City",
  "clubRating": "78.0",
  "clubPosition": "LCB",
  "clubJerseyNumber": 15.0,
  "clubJoinDate": "2017-06-15",
  "contractEndYear": 2023,
  "nationalTeam": "England",
  "nationalRating": 82.0,
  "nationalTeamPosition": "LCB",
  "nationalJerseyNumber": 6.0,
  "crossing": 44,
  "finishing": 43,
  "headingAccuracy": 87,
  "shortPassing": 77,
  "volleys": 41,
  "dribbling": 70,
  "curve": 38,
  "freekickAccuracy": 46,
  "longPassing": 72,
  "ballControl": 76,
  "acceleration": 39,
  "sprintSpeed": 54,
  "agility": 52,
  "reactions": 79,
  "balance": 58,
  "shotPower": 68,
  "jumping": 74,
  "stamina": 68,
  "strength": 89,
  "longShots": 45,
  "aggression": 84,
  "interceptions": 78,
  "positioning": 61,
  "vision": 60,
  "penalties": 44,
  "composure": 79,
  "marking": 81,
  "standingTackle": 84,
  "slidingTackle": 81,
  "GKDiving": 14,
  "GKHandling": 16,
  "GKKicking": 9,
  "GKPositioning": 14,
  "GKReflexes": 9
}