### Position Prediction
POST http://localhost:8081/fifa/players/predict-position
Content-Type: application/json

{
  "name": "S. Maguire",
  "fullName": "Sean Maguire",
  "birthDate": "1994-05-01",
  "age": 24,
  "heightCm": 175.26,
  "weightKgs": 68.0,
  "nationality": "Republic of Ireland",
  "overallRating": 71,
  "potential": 78,
  "valueEuro": 3400000.0,
  "wageEuro": 10000.0,
  "preferredFoot": "RIGHT",
  "internationalReputation": 1,
  "weakFoot": 3,
  "skillMoves": 3,
  "workRate": "High/ Medium",
  "bodyType": "Lean",
  "releaseClauseEuro": 7100000.0,
  "clubTeam": "Preston North End",
  "clubRating": "70.0",
  "clubJerseyNumber": 24.0,
  "clubJoinDate": "2017-07-24",
  "contractEndYear": 2020,
  "nationalTeam": "Republic of Ireland",
  "nationalRating": 74.0,
  "nationalTeamPosition": "SUB",
  "nationalJerseyNumber": 10.0,
  "crossing": 48,
  "finishing": 72,
  "headingAccuracy": 67,
  "shortPassing": 58,
  "volleys": 56,
  "dribbling": 73,
  "curve": 36,
  "freekickAccuracy": 33,
  "longPassing": 40,
  "ballControl": 71,
  "acceleration": 93,
  "sprintSpeed": 91,
  "agility": 88,
  "reactions": 64,
  "balance": 85,
  "shotPower": 63,
  "jumping": 70,
  "stamina": 76,
  "strength": 65,
  "longShots": 53,
  "aggression": 52,
  "interceptions": 28,
  "positioning": 73,
  "vision": 62,
  "penalties": 66,
  "composure": 67,
  "marking": 50,
  "standingTackle": 28,
  "slidingTackle": 22,
  "GKDiving": 15,
  "GKHandling": 10,
  "GKKicking": 13,
  "GKPositioning": 12,
  "GKReflexes": 12
}

### Price Prediction
POST http://localhost:8081/fifa/players/predict-price
Content-Type: application/json

{
  "name": "S. Maguire",
  "fullName": "Sean Maguire",
  "birthDate": "1994-05-01",
  "age": 24,
  "heightCm": 175.26,
  "weightKgs": 68.0,
  "nationality": "Republic of Ireland",
  "overallRating": 71,
  "potential": 78,
  "wageEuro": 10000.0,
  "preferredFoot": "RIGHT",
  "internationalReputation": 1,
  "weakFoot": 3,
  "skillMoves": 3,
  "workRate": "High/ Medium",
  "bodyType": "Lean",
  "releaseClauseEuro": 7100000.0,
  "clubTeam": "Preston North End",
  "clubRating": "70.0",
  "clubPosition": "ST",
  "clubJerseyNumber": 24.0,
  "clubJoinDate": "2017-07-24",
  "contractEndYear": 2020,
  "nationalTeam": "Republic of Ireland",
  "nationalRating": 74.0,
  "nationalTeamPosition": "SUB",
  "nationalJerseyNumber": 10.0,
  "crossing": 48,
  "finishing": 72,
  "headingAccuracy": 67,
  "shortPassing": 58,
  "volleys": 56,
  "dribbling": 73,
  "curve": 36,
  "freekickAccuracy": 33,
  "longPassing": 40,
  "ballControl": 71,
  "acceleration": 93,
  "sprintSpeed": 91,
  "agility": 88,
  "reactions": 64,
  "balance": 85,
  "shotPower": 63,
  "jumping": 70,
  "stamina": 76,
  "strength": 65,
  "longShots": 53,
  "aggression": 52,
  "interceptions": 28,
  "positioning": 73,
  "vision": 62,
  "penalties": 66,
  "composure": 67,
  "marking": 50,
  "standingTackle": 28,
  "slidingTackle": 22,
  "GKDiving": 15,
  "GKHandling": 10,
  "GKKicking": 13,
  "GKPositioning": 12,
  "GKReflexes": 12
}